version: '3'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: testing123
        # TODO: UNCOMMENT ME
        #volumes:
        #  - ./data/pit-0:/data/db
        #  - ./data/logs/mongodb:/logs



        #restart: on-failure
        networks:
          - traffic_net

    sds-tweet:
        build:
          context: ./
        image: sds-tweet:latest
        container_name: sds-tweet
        depends_on:
          - mongodb
        #ports:
        #  - 8000:8000
        networks:
        - traffic_net

networks:
  traffic_net:
    driver: bridge